name: SuperEffect
main: SE\Main
version: 1.0v
api: 3.0.0
author: GroupPluginer
commands:
  super:
      description: SuperEffect
  super2:
      description: SuperEffect2
  super3:
      description: SuperEffect3
